### ISSUE TITLE
Oracle Error Codes

### ISSUE THREAD

**Issue by akaustav** [gilcrest/raiser#1]
@gilcrest: I always wondered about the error messages provided by Oracle. Went thru your readme.md. Performed a quick Google search on ORA error codes. Found this: http://docs.oracle.com/cd/B28359_01/server.111/b28278/e19999.htm#sthref6269

The only SQLCODE error that I found between ORA-20000 thru ORA-20999 was ORA-20000. Am I missing something?

Ameet

**Comment by gilcrest** [comment]
Hey Ameet!  Yeah, so there is nothing between ORA-20000 and ORA-20999 - those exception numbers are reserved for end users (i.e.folks like you and me) to be able to raise specific database exceptions that are applicable only to the end user, I randomly chose ORA-20723 as it seemed like a good number, but it was arbitrary.

**Comment by gilcrest** [comment]
Closed as I believe I answered the question!  Check out https://docs.oracle.com/database/121/LNPLS/errors.htm#LNPLS99960 for more info though on raise_application_error proc.
